
reviews: {
  product: '23145',
    page: 0,
      count: 2,
        results: [
          {
            review_id: 308886,
            rating: 4,
            summary: 'This product was ok!',
            recommend: false,
            response: '',
            body: 'I really did not like this product solely because I am tiny and do not fit into it.',
            date: '2019-01-11T00:00:00.000Z',
            reviewer_name: 'mymainstreammother',
            helpfulness: 2,
            photos: [],
          },
          {
            review_id: 308885,
            rating: 5,
            summary: 'This product was great!',
            recommend: true,
            response: '',
            body: 'I really did or did not like this product based on whether it was sustainably sourced. Then I found out that its made from nothing at all.',
            date: '2019-01-01T00:00:00.000Z',
            reviewer_name: 'funtime',
            helpfulness: 9,
            photos: [],
          },
          {
            review_id: 308887,
            rating: 1,
            summary: 'This product was aweful',
            recommend: false,
            response: '',
            body: 'I really did not like this product solely because I am tiny and do not fit into it.',
            date: '2020-01-11T00:00:00.000Z',
            reviewer_name: 'screwge',
            helpfulness: 1,
            photos: [],
          },
          {
            review_id: 308888,
            rating: 5,
            summary: 'This product was amazing!',
            recommend: true,
            response: '',
            body: 'I really did or did not like this product based on whether it was sustainably sourced. Then I found out that its made from nothing at all.',
            date: '2021-02-19T00:00:00.000Z',
            reviewer_name: 'floydmaywether',
            helpfulness: 7,
            photos: [],
          },
          {
            review_id: 308889,
            rating: 5,
            summary: 'This product was amazing!',
            recommend: true,
            response: '',
            body: 'I really did or did not like this product based on whether it was sustainably sourced. Then I found out that its made from nothing at all.',
            date: '2019-01-01T00:00:00.000Z',
            reviewer_name: 'floydmaywether',
            helpfulness: 12,
            photos: [],
          },
          {
            review_id: 308890,
            rating: 5,
            summary: 'This product was dope',
            recommend: true,
            response: '',
            body: 'I really did not like this product solely because I am tiny and do not fit into it.',
            date: '2021-02-19T00:00:00.000Z',
            reviewer_name: 'somebody',
            helpfulness: 6,
            photos: [],
          },
          {
            review_id: 308891,
            rating: 5,
            summary: 'This product was LIT',
            recommend: true,
            response: '',
            body: 'I really did not like this product solely because I am tiny and do not fit into it.',
            date: '2021-02-19T00:00:00.000Z',
            reviewer_name: 'anonymous',
            helpfulness: 8,
            photos: [],
          },
          {
            review_id: 308887,
            rating: 1,
            summary: 'This product was aweful',
            recommend: false,
            response: '',
            body: 'I really did not like this product solely because I am tiny and do not fit into it.',
            date: '2020-01-11T00:00:00.000Z',
            reviewer_name: 'screwge',
            helpfulness: 1,
            photos: [],
          },
          {
            review_id: 308888,
            rating: 5,
            summary: 'This product was amazing!',
            recommend: true,
            response: '',
            body: 'I really did or did not like this product based on whether it was sustainably sourced. Then I found out that its made from nothing at all.',
            date: '2021-02-19T00:00:00.000Z',
            reviewer_name: 'floydmaywether',
            helpfulness: 7,
            photos: [],
          },
          {
            review_id: 308889,
            rating: 5,
            summary: 'This product was amazing!',
            recommend: true,
            response: '',
            body: 'I really did or did not like this product based on whether it was sustainably sourced. Then I found out that its made from nothing at all.',
            date: '2019-01-01T00:00:00.000Z',
            reviewer_name: 'floydmaywether',
            helpfulness: 12,
            photos: [],
          },
          {
            review_id: 308890,
            rating: 5,
            summary: 'This product was dope',
            recommend: true,
            response: '',
            body: 'I really did not like this product solely because I am tiny and do not fit into it.',
            date: '2021-02-19T00:00:00.000Z',
            reviewer_name: 'somebody',
            helpfulness: 6,
            photos: [],
          },
          {
            review_id: 308891,
            rating: 5,
            summary: 'This product was LIT',
            recommend: true,
            response: '',
            body: 'I really did not like this product solely because I am tiny and do not fit into it.',
            date: '2021-02-19T00:00:00.000Z',
            reviewer_name: 'anonymous',
            helpfulness: 8,
            photos: [],
          },
        ],
  };
reviewMeta: {
  product_id: '23145',
    ratings: {
    1: '1',
      4: '1',
        5: '3',
    },
  recommended: {
    false: '1',
      true: '1',
    },
  characteristics: {
    Fit: {
      id: 77676,
        value: '4.0000000000000000',
      },
    Length: {
      id: 77677,
        value: '3.5000000000000000',
      },
    Comfort: {
      id: 77678,
        value: '5.0000000000000000',
      },
    Quality: {
      id: 77679,
        value: '4.0000000000000000',
      },
  },
},

const postExample = {
  "summary": "I love it",
  "recommend": true,
  "response": "",
  "body": "Ohhh yeah! This product is so darn good.",
  "date": Date.now(),
  "reviewer_name": "bigballer",
  "helpfulness": 0,
  "reported": false,
  "rating": 5,
  "photos": [],
  "Fit": 4,
  "Length": 3,
  "Comfort": 4,
  "Quality": 3
}